name: "Build Docker Image"
description: "Build Docker image using Kaniko"
inputs:
  ref:
    description: "Ref. Git reference (branch, tag, or commit)"
    required: true
  registry:
    description: "Docker registry URL"
    required: true
  image:
    description: "Docker image name"
    required: true
  dockerfile:
    description: "Path to the Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Docker build script
      run: ${{ github.action_path }}/build_and_push.sh $PR_SHA
      shell: bash
