name: Build Docker Image
description: Build Docker image using Kaniko
inputs:
  ref:
    description: Ref. Git reference (branch, tag, or commit)
    required: true
  registry:
    description: Docker registry URL
    required: true
  image:
    description: Docker image name
    required: true
  dockerfile:
    description: Path to the Dockerfile
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: ">= 510.0.0"

    - name: Set Environment Variables
      shell: bash
      run: |
        # Extract repository name (karpatkey/my-repo -> my-repo)
        REPO_NAME="${GITHUB_REPOSITORY##*/}"

        REF="${{ inputs.ref }}"
        REF="${REF:-$GITREF}"

        REGISTRY="${{ inputs.registry }}"
        REGISTRY="${REGISTRY:-${DOCKER_REGISTRY:-europe-docker.pkg.dev/karpatkey-data-warehouse/karpatkey}}"

        IMAGE="${{ inputs.image }}"
        IMAGE="${IMAGE:-${DOCKER_IMAGE:-${REPO_NAME}}}"

        DOCKERFILE="${{ inputs.dockerfile }}"
        DOCKERFILE="${DOCKERFILE:-${DOCKER_DOCKERFILE:-./Dockerfile}}"
        DEFAULT_IMAGE=$REGISTRY/$IMAGE
        FULL_IMAGE_NAME="${DOCKER_IMAGE_NAME-$DEFAULT_IMAGE}"

        # Export for later steps
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        echo "REF=$REF" >> $GITHUB_ENV
        echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_ENV
        echo "FULL_IMAGE_NAME=$FULL_IMAGE_NAME" >> $GITHUB_ENV
      env:
        GITREF: ${{ github.head_ref || github.ref_name }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Run Docker build script
      run: ${{ github.action_path }}/build_and_push.sh $PR_SHA
      shell: bash

  update_prod_on_release:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    name: Update Prod Deployment in kpk-devops
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      TAG_NAME: ${{ github.event.release.tag_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout kpk-devops repo
        uses: actions/checkout@v4
        with:
          repository: karpatkey/kpk-devops
          token: ${{ secrets.KPK_DEVOPS_PAT }}
          ref: main

      - name: Update image tag in prod manifest
        run: |
          FILE_PATH="GitOps/${REPO_NAME}/deployment.yaml"
          sed -i "s|\(image: .*\):.*|\1:${TAG_NAME}|" "$FILE_PATH"

      - name: Commit and push changes
        run: |
          FILE_PATH="GitOps/${REPO_NAME}/deployment.yaml"
          FULL_IMAGE="europe-docker.pkg.dev/karpatkey-data-warehouse/karpatkey/${REPO_NAME}:${TAG_NAME}"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${TAG_NAME}"

          git config user.name "github-actions"
          git config user.email "ci@karpatkey.com"
          git add "$FILE_PATH"
          git commit -m "chore(ci): update prod image for ${REPO_NAME} to ${TAG_NAME}

          - Updated file: ${FILE_PATH}
          - New image tag: ${FULL_IMAGE}
          - Triggered by GitHub release: ${RELEASE_URL} "
          
          git push origin main

