name: 'Build Docker Image'
description: 'Build Docker image using Kaniko'
inputs:
  GIT_REF:
    description: 'Git reference (branch, tag, or commit)'
    required: true
  DOCKER_REGISTRY:
    description: 'Docker registry URL'
    required: true
  DOCKER_USERNAME:
    description: 'Docker username'
    required: true
  DOCKER_PASSWORD:
    description: 'Docker password'
    required: true
  DOCKER_IMAGE_NAME:
    description: 'Docker image name'
    required: true
  DOCKERFILE:
    description: 'Path to the Dockerfile'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: list
      run: ls -lah
      shell: bash

    - name: Run Docker build script
      run: ./build-docker-image/build_and_push.sh "$GIT_REF" "$DOCKER_REGISTRY" "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$DOCKER_IMAGE_NAME" "$DOCKERFILE"
      shell: bash