#!/bin/bash
set -xe

# Expect that your service account JSON is stored in a CI secret.
# Write the service account JSON content (from a secret, for example) to a file.
echo "$GCP_SA_JSON" > "$HOME/gcloud.json"

# Set the environment variable so that gcloud and client libraries pick it up.
export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud.json"

# Activate the service account using the JSON key.
gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"

# Configure Docker to use gcloud as a credential helper for your registry.
# Make sure that DOCKER_REGISTRY is set to your Artifact Registry domain (e.g. "europe-docker.pkg.dev").
gcloud auth configure-docker "$DOCKER_REGISTRY" --quiet

# Continue with your existing variables and tag calculations.
BRANCH_NAME=$(echo "$GIT_REF" | sed 's/[^a-zA-Z0-9]/-/g')
CURRENT_DATE=$(date -u +"%Y%m%d")
CURRENT_TIME=$(date -u +"%H%M%S")
PR_SHA=$(echo "$1" | cut -c1-7)
GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
DOCKER_TAG="${DOCKER_IMAGE_NAME}:${BRANCH_NAME}"
DOCKER_TAG_WITH_DATE="${DOCKER_IMAGE_NAME}:${BRANCH_NAME}-${CURRENT_DATE}-${CURRENT_TIME}"
DOCKER_TAG_WITH_PR_SHA="${DOCKER_IMAGE_NAME}:pr${PR_SHA}"

if [ -n "$GIT_TAG" ]; then
  DOCKER_TAG_WITH_GIT_TAG="${DOCKER_IMAGE_NAME}:${GIT_TAG}"
fi

# Optionally, ensure a cache directory exists
mkdir -p .cache

# Run Kaniko using the Docker config generated by gcloud.
docker run --rm \
  -v "$(pwd)":/workspace \
  -v "$(pwd)/.cache":/cache \
  -v "$HOME/.docker/config.json":/kaniko/.docker/config.json:ro \
  gcr.io/kaniko-project/executor:v1.23.2 \
  --context . \
  --build-arg GITHUB_PAT="$GITHUB_PAT" \
  --dockerfile /workspace/"$DOCKERFILE" \
  --destination "$DOCKER_TAG" \
  --destination "$DOCKER_TAG_WITH_DATE" \
  --destination "$DOCKER_TAG_WITH_PR_SHA" \
  $( [ -n "$GIT_TAG" ] && echo "--destination $DOCKER_TAG_WITH_GIT_TAG" ) \
  --cache=true \
  --cache-dir=/cache \
  --use-new-run \
  --single-snapshot \
  --snapshot-mode=redo \
  --compressed-caching=false \
  --cleanup \
  --cache-repo="$DOCKER_IMAGE_NAME"

echo "Image pushed to registry: $DOCKER_TAG"
if [ -n "$GIT_TAG" ]; then
  echo "Image also tagged with Git tag: $DOCKER_TAG_WITH_GIT_TAG"
fi
